#!/bin/bash

set -e

port=3900

version=$([ "$1" == "coffee" ] && echo "test-coffee" || echo "test")

# Find next available port
while lsof -i :$((++port)) >/dev/null; do true; done

# Spin a test server in the background
node ./test/server.js $port &>/dev/null &
server_pid=$!
trap "kill $server_pid" INT EXIT

node ./node_modules/.bin/mocha-phantomjs -s localToRemoteUrlAccessEnabled=true -s webSecurityEnabled=false "http://localhost:$port/test/${version}.html"
node ./node_modules/.bin/mocha-phantomjs -s localToRemoteUrlAccessEnabled=true -s webSecurityEnabled=false "http://localhost:$port/test/test-worker.html"
