#!/bin/bash

set -e

port=3900

# Find next available port
while lsof -i :$((++port)) >/dev/null; do true; done

# Spin a test server in the background
node ./script/server $port &>/dev/null &
server_pid=$!
trap "kill $server_pid" INT EXIT

STATUS=0

run() {
  node ./node_modules/.bin/mocha-phantomjs \
    -s localToRemoteUrlAccessEnabled=true \
    -s webSecurityEnabled=false \
    "$@" || STATUS=$?
}

run "http://localhost:$port/"
run "http://localhost:$port/test/test-worker.html"

exit $STATUS
