name: Greetings

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [closed]
  pull_request:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greet New Contributors for Creating New PR/Issues.
        uses: actions/first-interaction@v1
        if: github.event.action =='opened' && (github.event_name == 'pull_request' || github.event_name == 'issues')
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "@${{ github.actor }} Welcome to Fetch🥳 Thanks for opening this Issue 🙌, This Will definitely Improve our Project💖.While we are having a look at this. If you want to work on this then,feel free to self-assign and start working on it.📄  **Use `/assign` to self-assign this issue**."
          pr-message: "@${{ github.actor }} Thank you for Opening  pull request🥳. We will get back to you as soon as possible. Your patience is greatly appreciated! Thanks! 🥳.  PS: Please double check that you linked the corresponding issue."

      - name: Congratulate on every PR merge
        if: github.event_name == 'pull_request_target' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{tojson(github.event.number)}}
          body: |
            @${{ github.event.pull_request.user.login }} Hurray, your PR got merged 🥳. Thanks a bunch. Feel free to take another Issue.💖
